# Generated by Django 5.1.1 on 2024-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0002_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='private_files/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
