# Generated by Django 5.1.1 on 2024-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0003_groupmessage_file_message_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
