# Generated by Django 5.1.1 on 2024-12-07 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0004_message_receiver_deleted_message_sender_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_group_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
