# Generated by Django 5.1.1 on 2025-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0007_pushsubscription_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
