# Generated by Django 5.1.1 on 2025-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(default='group_avatars/default_group.png', upload_to='group_avatars/'),
        ),
    ]
