# Generated by Django 5.1.1 on 2025-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0011_message_deleted_by_message_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
