# Generated by Django 5.1.1 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0014_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10),
        ),
    ]
