# Generated by Django 5.1.1 on 2025-03-20 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0015_alter_userrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='can_be_contacted_by', to=settings.AUTH_USER_MODEL)),
                ('external_user', models.OneToOneField(limit_choices_to={'roles_role': 'externo'}, on_delete=django.db.models.deletion.CASCADE, related_name='contact_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
