# Generated by Django 5.1.1 on 2025-03-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0016_externalusercontacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusercontacts',
            name='external_user',
            field=models.OneToOneField(limit_choices_to=models.Q(('roles__role', 'externo')), on_delete=django.db.models.deletion.CASCADE, related_name='contact_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
