# Generated by Django 5.1.1 on 2025-03-24 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0017_alter_externalusercontacts_external_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusercontacts',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='contacted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
