# Generated by Django 5.1.1 on 2025-03-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0018_alter_externalusercontacts_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalusercontacts',
            options={'verbose_name': 'External contact', 'verbose_name_plural': 'External contacts'},
        ),
        migrations.AlterField(
            model_name='externalusercontacts',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='contacted_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Permitidos'),
        ),
        migrations.AlterField(
            model_name='externalusercontacts',
            name='external_user',
            field=models.OneToOneField(limit_choices_to=models.Q(('roles__role', 'externo')), on_delete=django.db.models.deletion.CASCADE, related_name='contact_list', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Externo'),
        ),
    ]
