# Generated by Django 5.1.1 on 2025-03-24 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0020_alter_externalusercontacts_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusercontacts',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='contacted_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios permitidos'),
        ),
    ]
