# Generated by Django 5.1.1 on 2025-03-24 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0021_alter_externalusercontacts_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(default='group_avatars/default_group.png', upload_to='group_avatars/', verbose_name='Imagen del Grupo'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creador del Grupo'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='group_chats', to=settings.AUTH_USER_MODEL, verbose_name='Miembros disponibles'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Grupo'),
        ),
    ]
