# Generated by Django 5.1.1 on 2025-03-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0022_alter_groupchat_avatar_alter_groupchat_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del Mensaje'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_for_all',
            field=models.BooleanField(default=False, verbose_name='Eliminado para Todos'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='private_files/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado por el Destinatario'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado por el Remitente'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Envío'),
        ),
    ]
