# Generated by Django 5.1.1 on 2025-03-24 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0023_alter_message_content_alter_message_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del Mensaje'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='deleted_for_all',
            field=models.BooleanField(default=False, verbose_name='Eliminado para todos'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_files/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='appSMS.groupchat', verbose_name='Nombre del Grupo'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Envío'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del mensaje'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_for_all',
            field=models.BooleanField(default=False, verbose_name='Eliminado para todos'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado por el destinatario'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado por el remitente'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de envío'),
        ),
    ]
