# Generated by Django 5.1.1 on 2025-03-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0025_groupmemberrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmemberrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='appSMS.groupchat', verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='role',
            field=models.CharField(blank=True, choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=10, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
