# Generated by Django 5.1.1 on 2025-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0026_alter_groupmemberrole_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
    ]
