# Generated by Django 5.1.1 on 2025-03-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0027_alter_groupchat_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol del sistema',
                'verbose_name_plural': 'Roles del sistema',
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='appSMS.usersystemrole')),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
