# Generated by Django 5.1.1 on 2025-03-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0028_usersystemrole_userroleassignment_delete_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'verbose_name': 'Grupo de chat', 'verbose_name_plural': 'Grupos de chats'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Mensaje de grupo', 'verbose_name_plural': 'Mensajes de grupos'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensaje de chat', 'verbose_name_plural': 'Mensajes de los chats'},
        ),
    ]
