# Generated by Django 5.1.1 on 2025-03-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0029_alter_groupchat_options_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de permiso',
                'verbose_name_plural': 'Tipos de permisos',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='appSMS.permissiontype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='appSMS.usersystemrole')),
            ],
            options={
                'verbose_name': 'Permiso rol',
                'verbose_name_plural': 'Permisos rol',
                'unique_together': {('role', 'permission_type')},
            },
        ),
    ]
