# Generated by Django 5.1.1 on 2025-03-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0030_permissiontype_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='allowed',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='appSMS.permissiontype', verbose_name='Tipo de permiso'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='appSMS.usersystemrole', verbose_name='Rol'),
        ),
    ]
