# Generated by Django 5.1.1 on 2025-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0031_alter_rolepermission_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='permissiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Permiso'),
        ),
    ]
