# Generated by Django 5.1.1 on 2025-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0032_alter_permissiontype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='allowed',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
