# Generated by Django 5.1.1 on 2025-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0033_alter_rolepermission_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontype',
            name='code',
            field=models.SlugField(blank=True, help_text='Identificador técnico del permiso (no cambiar una vez creado)', null=True, unique=True, verbose_name='Código'),
        ),
    ]
