# Generated by Django 5.1.1 on 2025-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0034_permissiontype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='code',
            field=models.SlugField(help_text='Identificador técnico del permiso (no cambiar una vez creado)', unique=True, verbose_name='Código'),
        ),
    ]
