# Generated by Django 5.1.1 on 2025-03-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0035_alter_permissiontype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_alias',
            field=models.CharField(blank=True, help_text='Nombre que se muestra al enviar el mensaje si el usuario es anónimo', max_length=150, null=True),
        ),
    ]
