# Generated by Django 5.1.1 on 2025-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0036_message_sender_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=255, verbose_name='Sala de chat'),
        ),
    ]
