# Generated by Django 5.1.1 on 2025-04-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0037_alter_message_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmemberrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmemberrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmemberrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='groupchat',
            options={'verbose_name': 'Grupos de chats', 'verbose_name_plural': 'Grupos de chats'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Mensajes de grupos', 'verbose_name_plural': 'Mensajes de grupos'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensajes de los chat', 'verbose_name_plural': 'Mensajes de los chats'},
        ),
        migrations.AlterModelOptions(
            name='permissiontype',
            options={'verbose_name': 'Tipos de permisos', 'verbose_name_plural': 'Tipos de permisos'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Permisos rol', 'verbose_name_plural': 'Permisos rol'},
        ),
        migrations.AlterModelOptions(
            name='usersystemrole',
            options={'verbose_name': 'Roles del sistema', 'verbose_name_plural': 'Roles del sistema'},
        ),
        migrations.CreateModel(
            name='AllowedContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='visible_for_users', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios permitidos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario con contacto limitado')),
            ],
            options={
                'verbose_name': 'Contactos permitidos',
                'verbose_name_plural': 'Contactos permitidos',
            },
        ),
        migrations.DeleteModel(
            name='ExternalUserContacts',
        ),
        migrations.DeleteModel(
            name='GroupMemberRole',
        ),
    ]
