# Generated by Django 5.1.1 on 2025-04-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0038_alter_groupmemberrole_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcontacts',
            options={'verbose_name': 'Asignar usuarios', 'verbose_name_plural': 'Asignar usuarios'},
        ),
        migrations.AlterField(
            model_name='allowedcontacts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
