# Generated by Django 5.1.1 on 2025-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0039_alter_allowedcontacts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcontacts',
            options={'verbose_name': 'Contactos asignados', 'verbose_name_plural': 'Contactos asignados'},
        ),
    ]
