# Generated by Django 5.1.1 on 2025-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0040_alter_allowedcontacts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='allowed',
            field=models.BooleanField(default=True, verbose_name='Bloqueado'),
        ),
    ]
