# Generated by Django 5.1.1 on 2025-04-08 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0041_alter_rolepermission_allowed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='appSMS.groupchat', verbose_name='Grupo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='appSMS.usersystemrole', verbose_name='Rol asignado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol en grupo',
                'verbose_name_plural': 'Roles en grupos',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True, verbose_name='Bloqueado')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='appSMS.groupchat', verbose_name='Grupo')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='appSMS.permissiontype', verbose_name='Permiso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='appSMS.usersystemrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol en grupo',
                'verbose_name_plural': 'Permisos de rol en grupo',
                'unique_together': {('group', 'role', 'permission_type')},
            },
        ),
    ]
