# Generated by Django 5.1.1 on 2025-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0042_groupmemberrole_grouprolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='sender_alias',
            field=models.CharField(blank=True, help_text='Nombre que se muestra al enviar el mensaje si el usuario es anónimo', max_length=150, null=True),
        ),
    ]
