# Generated by Django 5.1.1 on 2025-04-17 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0043_groupmessage_sender_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Estado de lectura')),
                ('date_read', models.DateField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_lectura', to='appSMS.message', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_lectura_mensajes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lectura mensajes de chats',
                'verbose_name_plural': 'Lecturas mensajes de chats',
            },
        ),
    ]
