# Generated by Django 5.1.1 on 2025-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0044_messagereadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereadstatus',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de lectura'),
        ),
    ]
