# Generated by Django 5.1.1 on 2025-04-21 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0045_alter_messagereadstatus_date_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Estado de lectura')),
                ('date_read', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de lectura')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_lectura', to='appSMS.groupmessage', verbose_name='Mensaje de Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_lectura_mensajes_grupo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lectura de mensajes de grupos',
                'verbose_name_plural': 'Lecturas de mensajes de grupos',
            },
        ),
    ]
