# Generated by Django 5.1.1 on 2025-04-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0046_groupmessagereadstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessagereadstatus',
            options={'verbose_name': 'Lectura mensajes de grupos', 'verbose_name_plural': 'Lecturas mensajes de grupos'},
        ),
    ]
