# Generated by Django 5.1.1 on 2025-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0047_alter_groupmessagereadstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystemrole',
            name='alias_public',
            field=models.CharField(blank=True, help_text='Nombre visible si el usuario tiene activado el permiso anónimo (ej: Soporte)', max_length=100, null=True, verbose_name='Alias público'),
        ),
    ]
