# Generated by Django 5.1.1 on 2025-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSMS', '0048_usersystemrole_alias_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystemrole',
            name='alias_public',
        ),
    ]
