version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_db:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  sqlite_db:
  redis_data:
  static_volume:
  media_volume: